-- Database Optimization Script for Mnemonix
-- Run these in your Supabase SQL Editor to improve performance for 50k+ users

-- 1. Index for checking existing mnemonics globally
-- This accelerates search lookups for words that have already been generated by anyone
CREATE INDEX IF NOT EXISTS idx_mnemonics_word_lang ON mnemonics(word, language);

-- 2. Index for user-specific words
-- This accelerates the dashboard, flashcards, and profile views
CREATE INDEX IF NOT EXISTS idx_user_words_user_id ON user_words(user_id);
CREATE INDEX IF NOT EXISTS idx_user_words_created_at ON user_words(created_at DESC);

-- 3. Index for social feed
-- Accelerates loading global posts for the specific user language
CREATE INDEX IF NOT EXISTS idx_posts_language_created_at ON posts(language, created_at DESC);

-- 4. Index for user profiles 
-- Accelerates profile lookups during auth and social interactions
CREATE INDEX IF NOT EXISTS idx_profiles_id ON profiles(id);

-- 5. Index for Payments (High traffic for webhooks)
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_payme_trans_id ON payments(payme_transaction_id);

-- 6. Full Text Search Index (Optional but recommended for large datasets)
-- Allows users to search for keywords within the story as the dataset grows
-- ALTER TABLE mnemonics ADD COLUMN word_search_vector tsvector GENERATED ALWAYS AS (to_tsvector('english', word)) STORED;
-- CREATE INDEX idx_mnemonics_fts ON mnemonics USING GIN (word_search_vector);
